import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import "./globals.css";
import "../public/css/bootstrap-select.min.css";
import "../public/css/bootstrap.css";
import "../public/css/animate.min.css";
import "../public/css/animation.css";
import Sidebar from "@/components/Sidebar";
import Header from "@/components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`body ${inter.className} `}>
        <Header />
        <Sidebar /> {children}
      </body>
    </html>
  );
}
